### ISSUE TITLE
optipng not in Homebrew

### ISSUE THREAD

**Issue by hugovk** [ajslater/picopt#10]
The readme has for OS X:

> `brew install optipng pngout jpeg gifsicle`

But optipng isn't in Homebrew because it's binary only: https://github.com/Homebrew/homebrew/pull/5185

The binary is here: http://www.jonof.id.au/pngout

(The other things brew install ok.)

**Comment by ajslater** [comment]
I found this gist looking around, but I guess I should update my docs
https://gist.github.com/BrianGilbert/6664465

**Comment by ajslater** [comment]
The documentation has been corrected.
