### ISSUE TITLE
picopt could use a --preserve option

### ISSUE THREAD

**Issue by rallant92** [ajslater/picopt#12]
When compressing 10 to 20 year old photo collections, I don't want their attributes like time changed.  I want the files to be the same, only smaller.

The --preserve option usually controls this.  I see this from 'man cp':

```
       -p     same as --preserve=mode,ownership,timestamps

       --preserve[=ATTR_LIST]
              preserve the specified attributes (default: mode,ownership,time‐
              stamps),  if  possible  additional  attributes:  context, links,
              xattr, all

```

Preserving the mode and ownership are important too, so that other users can access the files after shrinkage.

**Comment by ajslater** [comment]
[picopt 4.0.0](https://github.com/ajslater/picopt/releases/tag/v4.0.0) includes a `--preserve` option. However it does not include an attribute list.

```
  -p, --preserve        Preserve file attributes (uid, gid, mode, mtime) after
                        optimization.
```
