### ISSUE TITLE
Support additional compressors

### ISSUE THREAD

**Issue by haarp** [ajslater/picopt#14]
For PNG, zopflipng compresses slightly better than even pngout. For JPEG there is a jpegoptim.

**Comment by ajslater** [comment]
Thanks, I'll investigate zopfli. Am also considering pngwolf support.

As far as jpeg goes, jpegrescan was the best, although poorly packaged, but now mozjpeg obsoletes that and everything else. Other jpeg optimizers have been left in for backwards compatibility only.

**Comment by ajslater** [comment]
less concerned with this now that WEBP lossless is supported on all browsers.
