### ISSUE TITLE
AttributeError: (dict) object has not attribute 'iteritems'

### ISSUE THREAD

**Issue by noisytoken** [ajslater/picopt#22]
picopt gives me following error when i tried to run the following command:

```
$: picopt * jpg
AttributeError: (dict) object has not attribute 'iteritems'
```

I am using Ubuntu with Python3. I tried removing `iteritems` to `items` but then it throws different error:

`TypeError: unorderable types: NoneType() >NoneType()`

**Comment by ajslater** [comment]
fixed in v1.5.2
