### ISSUE TITLE
Modifying argument list for external tools via command line arguments

### ISSUE THREAD

**Issue by return1** [ajslater/picopt#25]
It would be a nice feature to have control over the argument list sent to different external tools. For example i would like to set the mozjpeg quality to 60%.
At the moment i would have to change the 

`_MOZJPEG_ARGS = ['mozjpeg']` 
to 
`_MOZJPEG_ARGS = ['mozjpeg','-quality','60']`

and make a fork. Any hints or ideas? Thanks!

**Comment by ajslater** [comment]
WONTFIX
picopt is dedicated to maximum lossless file size reduction.
