### ISSUE TITLE
skip broken flag

### ISSUE THREAD

**Issue by drmax24** [ajslater/picopt#31]
1. Can you add an option to skip broken images?

We have thousands of images and few of them are broken. Can we skip them somehow?

2. I'm not sure if my images were broken BEFORE running picopt. Or may be it is picopt that breaks them. Can you add a dry run flag that will show problematic images?

**Comment by drmax24** [comment]
*BUMP*

We need this! )

**Comment by ajslater** [comment]
The –list or –test flag will show broken images.
The broken images will be logged in all modes.
