### ISSUE TITLE
rubbish files

### ISSUE THREAD

**Issue by drmax24** [ajslater/picopt#32]
after running picopt several times (with errors) i have rubbish files:

drwxrwxrwx  2 www  www    1024 May 13 01:55 .
drwxrwxrwx  9 www  www     512 Jun 20  2016 ..
-rwxrwxrwx  1 www  www  317020 Jun 20  2016 CCB0734_12.PNG
-rwxrwxrwx  1 www  www  317020 Jun 20  2016 CCB0734_12.PNG.picopt-optimized.png
-rwxrwxrwx  1 www  www  317020 Jun 20  2016 CCB0734_12.PNG.picopt-optimized.png.picopt-optimized.png
-rwxrwxrwx  1 www  www  317020 Jun 20  2016 CCB0734_12.PNG.picopt-optimized.png.picopt-optimized.png.picopt-optimized.png
-rwxrwxrwx  1 www  www  317020 Jun 20  2016 CCB0734_12.PNG.picopt-optimized.png.picopt-optimized.png.picopt-optimized.png.picopt-optimized.png
-rwxrwxrwx  1 www  www  317020 Jun 20  2016 CCB0734_12.PNG.picopt-optimized.png.picopt-optimized.png.picopt-optimized.png.picopt-optimized.png.picopt-optimized.png

i run 

find . -name "*picopt-optimized*" -type f -delete

to fix it.

I think it's not ok that picopt multiplies it's own temporary files

**Comment by ajslater** [comment]
Picopt is now better about not crashing an leaving behind temporary files.
As of picopt 3.0 picopt now cleans up its temporary files on subsequent runs and does not waste time optimizing them.
