### ISSUE TITLE
ValueError: Decompressed Data Too Large

### ISSUE THREAD

**Issue by drmax24** [ajslater/picopt#33]
When bulk optimizing images on my server i've got error for some of my files:

ValueError: Decompressed Data Too Large for originals.

Can i do anything about it? I have 64 of GB Ram...

**Comment by drmax24** [comment]
picopt -Mr *

in theory it should remove exif. but it can not start because exif is too big probably for it to handle

**Comment by ajslater** [comment]
I'd need a sample image to experiment with. 
Occasionally some images will trigger the Pillow image library's compression bomb defense and will be skipped.
