### ISSUE TITLE
build-system in pyproject.toml: build-backend must be a string

### ISSUE THREAD

**Issue by carlosal1015** [ajslater/picopt#70]
Hi, [we are having a problem with recent python 3.11](https://aur.archlinux.org/packages/picopt#comment-913719) in this line when we install using [build frontend](https://github.com/pypa/build/blob/0.10.0/src/build/__init__.py#L221) (the same with `pip install picopt` method).
https://github.com/ajslater/picopt/blob/11acd82f8e1af137066225346cd324703d9aea83/pyproject.toml#L3

I understand that [python 3.11 only accepts a string, not a list](https://realpython.com/python311-tomllib/#learn-basic-toml).

**Comment by ajslater** [comment]
[picopt 4.0.0](https://github.com/ajslater/picopt/releases/tag/v4.0.0) now builds with python 3.11 correctly with a build-backend string.

**Comment by carlosal1015** [comment]
Yay, thanks, [patch is not required anymore](https://aur.archlinux.org/cgit/aur.git/commit/?h=picopt&id=906359c0dbea6ae4cb008cb228b0ff74db70a364).
